language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

sudo: false

install:
  - pip install tox python-coveralls
  - sed -r
    -e "s,(MAPIT_DB_USER:) 'mapit',\\1 'postgres',"
    conf/general.yml-example > conf/general.yml

script:
  - tox

after_success:
  - coveralls
