language: python

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
      - postgresql-9.6-postgis-2.3-scripts

matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

sudo: false

install:
  - pip install -r test_requirements.txt
  - pip install -r script_requirements.txt
  - pip install tox python-coveralls
  - sed -r
    -e "s,(MAPIT_DB_USER:) 'mapit',\\1 'postgres',"
    conf/general.yml-example > conf/general.yml

before_script:
  - createdb -U postgres mapit
  - psql -U postgres -d mapit -c 'CREATE EXTENSION postgis;'

script:
  - tox

after_success:
  - coveralls
